# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
#   exclude:
#     - path/to/excluded/files/**

linter:
  rules:
    - always_declare_return_types
    #    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    #    - always_specify_types
    - annotate_overrides
    - avoid_annotating_with_dynamic
    #    - avoid_as
    #    - avoid_bool_literals_in_conditional_expressions # under review (see #1068)
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    #    - avoid_classes_with_only_static_members
    #    - avoid_double_and_int_checks # under review (see #1068)
    #    - avoid_field_initializers_in_const_classes # under review (see #1068)
    #    - avoid_function_literals_in_foreach_calls
    #    - avoid_implementing_value_types
    #    - avoid_js_rounded_ints # under review (see #1068)
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    #    - avoid_private_typedef_functions # under review (see #1068)
    #    - avoid_renaming_method_parameters # under review (see #1068)
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    #    - avoid_single_cascade_in_expression_statements # under review (see #1068)
    - avoid_slow_async_io
    #    - avoid_types_as_parameter_names # under review (see #1068)
    #    - avoid_types_on_closure_parameters
    #    - avoid_unused_constructor_parameters # under review (see #1068)
    #    - avoid_void_async # under review (see #1068)
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    #    - cascade_invocations
    #    - close_sinks # https://github.com/dart-lang/linter/issues/268
    - comment_references
    #    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    #    - file_names # under review (see #1068)
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - lines_longer_than_80_chars # under review (see #1068)
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - non_constant_identifier_names
    #    - omit_local_variable_types
    #    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    #    - prefer_bool_in_asserts # Deprecated
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    #    - prefer_const_declarations # under review (see #1068)
    #    - prefer_const_literals_to_create_immutables # under review (see #1068)
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    - prefer_final_fields
    #    - prefer_final_locals
    - prefer_foreach
    #    - prefer_function_declarations_over_variables
    #    - prefer_generic_function_type_aliases # under review (see #1068)
    - prefer_initializing_formals
    #    - prefer_interpolation_to_compose_strings
    - prefer_iterable_whereType
    #    - prefer_mixin
    - prefer_single_quotes
    #    - prefer_typing_uninitialized_variables # under review (see #1068)
    #    - prefer_void_to_null # under review (see #1068)
    #    - public_member_api_docs
    #    - sort_constructors_first
    #    - sort_unnamed_constructors_first
    #    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    #    - type_annotate_public_apis
    - unnecessary_brace_in_string_interps
    #    - unnecessary_const # under review (see #1068)
    - unnecessary_getters_setters
    - unnecessary_lambdas
    #    - unnecessary_new # under review (see #1068)
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    #    - unnecessary_parenthesis # under review (see #1068)
    #    - unnecessary_statements # under review (see #1068)
    - unnecessary_this
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
#    - void_checks # under review (see #1068)