name: itch_io
description: Unofficial Itch.io REST API wrapper for the Dart Language.
version: 1.0.0
homepage: https://gihub.com/xenoken/itch-io
author: Kennedy Tochukwu Ekeoha <ekeohak@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
