name: itch_io
description: Unofficial itch.io REST API wrapper for the Dart Language. Supports credentials, user's profile info and games.
version: 2.0.0
homepage: https://github.com/xenoken/itch_io
repository: https://github.com/xenoken/itch_io
author: Ken Ekeoha <ekeohak@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
